name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: |
        python -m build

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/*

    - name: Build Docker image
      run: |
        docker build -t dezocode/mcp-system:${{ github.ref_name }} .
        docker build -t dezocode/mcp-system:latest .

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        docker push dezocode/mcp-system:${{ github.ref_name }}
        docker push dezocode/mcp-system:latest

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        body: |
          ## Changes in this Release
          
          See [CHANGELOG.md](https://github.com/dezocode/mcp-system/blob/main/CHANGELOG.md) for details.
          
          ## Installation
          
          ### One-Click Installation
          ```bash
          curl -sSL https://raw.githubusercontent.com/dezocode/mcp-system/main/install.sh | bash
          ```
          
          ### Docker
          ```bash
          docker run --rm -it dezocode/mcp-system:${{ github.ref_name }} mcp-universal --help
          ```
          
          ### PyPI
          ```bash
          pip install mcp-system
          ```